### ISSUE TITLE
Getting error rate

### ISSUE THREAD

**Issue by yaron-e** [lemmingapex/trilateration#18]
How do you get the error rate from the `RealVector` variable? In distance form? 

```
// error and geometry information; may throw SingularMatrixException depending the threshold argument provided

RealVector standardDeviation = optimum.getSigma(0);
RealMatrix covarianceMatrix = optimum.getCovariances(0);
```

**Comment by lemmingapex** [comment]
What is "error rate"?

**Comment by yaron-e** [comment]
By "error rate" I meant standard deviation. 

How would the standard deviation be obtained from the `RealVector`  variable?

**Comment by kburfi** [comment]
The standard deviation has the same dimension as your input variables. E. g. For two dimensional multilateration it is therefore also two dimensional.

**Comment by yaron-e** [comment]
How do you get the dimension of the standard deviation from the `RealVector`? Are you using the `getDimension()` method?

**Comment by kburfi** [comment]
Yes this method returns the dimension of your vector. But as I read this thread it strikes me that you are not sure about the theory behind this library. You already know the dimension of the standard deviation.

In case of the example input values of this library you have two dimensions for each position. This means you have x- and y-coordinates:
`double[][] positions = new double[][] { { 5.0, -6.0 }, { 13.0, -15.0 }, { 21.0, -3.0 }, { 12.4, -21.2 } };`

From the calculated optimum the standard deviation can be estimated. It also has the same dimension as the input positions meaning x and y.
Now referring to your original question - the estimated standard deviation has nothing to do with any kind of error.
You cannot get correct information about the error to the real location because you have to know this location before....
